server:
  port: ${ORDER_SERVER_PORT}

spring:
  application:
    name: order-service

  # == DATABASE ==
  r2dbc:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    topic:
      order-creation-requested: ${ORDER_CREATTION_REQUESTED}
      stock-reservation-result: ${STOCK_RESERVATION_RESULT}
      order-cancel: ${ORDER_CANCEL}

jwt:
  jwks-uri: ${JWT_JWKS_URI}

services:
  product-service:
    url: ${PRODUCT_SERVICE_URL}
  user-service:
    url: ${USER_SERVICE_URL}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.Loqal.orderservice: DEBUG

outbox:
  relay:
    delay: 10000 # 10 seconds