spring:
  application:
    name: loqal-catalog
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    topic:
      order-creation-requested: ${TOPIC_ORDER_CREATION_REQUESTED:order-creation-requested}
      stock-reservation-result: ${TOPIC_STOCK_RESERVATION_RESULT:stock-reservation-result}
      order-cancel: ${TOPIC_ORDER_CANCEL:order-cancel}
      order-cancel-dlt: ${TOPIC_ORDER_CANCEL_DLT:order-cancel-dlt}
  r2dbc:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

jwt:
  jwks-uri: ${JWT_JWKS_URI:http://localhost:8080/.well-known/jwks.json}

springdoc:
  api-docs.path: /custom-docs
