spring:
  application:
    name: product-service
  kafka:
    topic:
      order-cancel: ${ORDER_CANCEL}
      stock-reservation-result: ${STOCK_RESERVATION_RESULT}
      order-cancel-dlt: ${ORDER_CANCEL_DLT}
      order-creation-requested: ${ORDER_CREATTION_REQUESTED}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  r2dbc:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port: ${PRODUCT_SERVER_PORT}
  
jwt:
  jwks-uri: ${JWT_JWKS_URI}

services:
  product-service:
    url: ${PRODUCT_SERVICE_URL}
  user-service:
    url: ${USER_SERVICE_URL}