spring:
  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO_SETTING}
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: ProductService

server:
  port: ${PRODUCT_SERVER_PORT}
jwt:
  jwks-uri: ${JWT_JWKS_URI}